### ISSUE TITLE
Entities Pages

### ISSUE THREAD

**Issue by smcgregor** [responsible-ai-collaborative/aiid#1006]
With the recent inclusion of naming the developers, deployers, and harmed parties associated with incidents, we now have the ability to create pages highlighting the incidents generated and responded to by various companies.

(design is WIP)

# Pages

## Entity Pages

The entity pages are populated from the information found [here](https://incidentdatabase.ai/apps/incidents) and are hosted at `/entity/ENTITYNAME`

The page should include card headings for,

* Developer and Deployer (only if needed)
* Developer (only if needed)
* Deployer (only if needed)

These cards should use the incident cards as detailed below.

There should also be a section listing the related entities, such as all the other entities deploying the entities technology, or whose technology the entity is deploying.

## Entities Page

In addition to the detail view for an individual entity, there should be a summary page operating across all entities. The information presented should include summary statistics across all entities/incidents/reports,

* Developer Incident Counts
* Deployer Incident Counts

This should be hosted at `/entities`

## Entities Card

This should be a small card giving the top ~3 entities by incident count for the developer and deployer and additionally link to the entities page.

## Incident Card

We currently do not have a standard cards for incidents (they are all for reports). These incident cards should be used in the entity pages and listed under the appropriate headings.

## Integrations

The entity pages should be linked to throughout the app.

* The entity page should be linked to on the citation pages
* The `/apps/incidents` entities should link to the entity page
* The Entities Card should be on the landing page (fairly high up)
* The entities page should be linked to in the navigation consistent with @lmcnulty's nav design change 

# Future

We want to credit companies that respond to incidents with some sort of progress indicator. For example, [this report](https://incidentdatabase.ai/cite/51#r1765) is Knightscope's response to one of their incidents and we should reward this by showing on the entity pages and page that they have done this.

**Comment by cesarvarela** [comment]
- [ ] Entity Pages
- [ ] Entities Page
- [ ] Entities Card
- [ ] Incident Card
- [ ] The entity page should be linked to on the citation pages
- [ ] The /apps/incidents entities should link to the entity page
- [ ] The Entities Card should be on the landing page (fairly high up)
- [ ] The entities page should be linked to in the navigation consistent with @lmcnulty's nav design change

**Comment by smcgregor** [comment]
Last remaining issue here: https://github.com/responsible-ai-collaborative/aiid/issues/1436
