### ISSUE TITLE
User Account Enhancements to Support Data Activities

### ISSUE THREAD

**Issue by Janetbananet** [responsible-ai-collaborative/aiid#1783]
We need to enhance the user accounts to support users who become more active in submitting and editing data into the AIID. This is an Initiative that should have a batch of corresponding stories as individual GitHub Issues that will themselves have developer work associated with them.

Below is a list of stories to start with and corresponding GitHub Issue numbers. The list may grow depending on what is determined is needed currently from the user accounts.

- [ ] Allow users to create a "profile" with an image, bio (any other standard "profile" items).
- [ ] #1759 
- [ ] Automatically subscribe the user to reports or incidents the user submitted or made changes to
- [ ] Display in account details page all reports the user has submitted and whether they are/were rejected/pending review/ingested
- [ ] Display in account details page all reports and/or incidents the user has made edits to.
- [ ] Display in account details the user role or badge (i.e. Editor)

**Comment by smcgregor** [comment]
For new work, I think `Display in account details page all reports the user has submitted and whether they are/were rejected/pending review/ingested` is a good next target along with some page that shows all changes that have been made to the data in reverse chronological order.
