### ISSUE TITLE
[Facebook authentication] Transfer FB App Ownership to RAIC/AIID

### ISSUE THREAD

**Issue by pdcp1** [responsible-ai-collaborative/aiid#2586]
We currently have the Facebook Apps (Staging and Production) associated with Pablo's and Sean's accounts.

The app's ownership should be transferred to a RAIC/AIID Business account following this FB documentation https://developers.facebook.com/docs/development/create-an-app/transfer-an-app

In my opinion, the best way to do that is by adding someone from RAIC/AIID infrastructure team as an Admin to the existing apps.

In the future, if they want to associate the apps with the RAIC/AIID Facebook Business account, we should create and verify a FB Business account and start the Business verification process, or link those apps to the existing FB Business if it already exists.

<img width="1779" alt="Screenshot 2024-01-24 at 10 34 13" src="https://github.com/responsible-ai-collaborative/aiid/assets/6564809/8c754a59-b24b-41a1-9ee4-25dcd415e6e2">

Additional FB documentation: https://www.facebook.com/business/help/236817717885919

## Sub-Tasks
- [x] Create and verify RAIC business account
### For Staging
- [x] Transfer FB App ownership to RAIC business account
- [x] Submit Data Use Checkup
- [x] Test Facebook login

### For Production
- [x] Transfer FB App ownership to RAIC business account
- [ ] Submit Data Use Checkup
- [ ] Test Facebook login

**Comment by pdcp1** [comment]
Ownership transferred to RAIC business account!

**Comment by pdcp1** [comment]
@kepae 
**Update:** Staging Facebook login is working.

We have the Production Facebook App Id hardcoded in the Realm auth config file, but it can be modified through the [Atlas UI](https://services.cloud.mongodb.com/groups/6153eea15b27c6494839aa4e/apps/6153efd1bf5a3119b90c2e53/auth/providers/oauth2-facebook)

This is the configuration file that I mentioned:
https://github.com/responsible-ai-collaborative/aiid/blob/70b5d70681af8543d2cb1424303b34ad784bc656/site/realm/auth/providers.json#L28

Kevin, please go ahead with the Data Use Checkup submission process for Production.

**Comment by kepae** [comment]
Thanks Pablo!

**Comment by pdcp1** [comment]
https://incidentdatabase.ai Facebook login is currently working 👍
