### ISSUE TITLE
Tracking Issue: Playright Test Migration

### ISSUE THREAD

**Issue by kepae** [responsible-ai-collaborative/aiid#2806]
**This is now a tracking issue.**

- [x] https://github.com/responsible-ai-collaborative/aiid/issues/2804
- [x] #2836 
- [x] https://github.com/responsible-ai-collaborative/aiid/issues/2825
- [x] https://github.com/responsible-ai-collaborative/aiid/pull/2839
- [x] #2836 
- [x] #2840 
- [x] #2842 
- [x] https://github.com/responsible-ai-collaborative/aiid/issues/2845
- [x] #2847 
- [x] https://github.com/responsible-ai-collaborative/aiid/issues/2850
- [x] https://github.com/responsible-ai-collaborative/aiid/issues/2852
- [x] https://github.com/responsible-ai-collaborative/aiid/issues/2854
- [x] #2863
- [x] #2874 
- [x] #2875 
- [x] #2877 
- [x] https://github.com/responsible-ai-collaborative/aiid/issues/2878
- [x] https://github.com/responsible-ai-collaborative/aiid/issues/2879
- [x] #2895 
- [x] #2897 
- [x] #2900 
- [x] #2902 
- [x] #2905 
- [x] #2906 
- [x] #2908 
- [x] #2909 
- [x] https://github.com/responsible-ai-collaborative/aiid/issues/2918
- [x] https://github.com/responsible-ai-collaborative/aiid/issues/2919
- [x] https://github.com/responsible-ai-collaborative/aiid/issues/2922
- [x] https://github.com/responsible-ai-collaborative/aiid/issues/2924
- [x] https://github.com/responsible-ai-collaborative/aiid/issues/2932
- [x] https://github.com/responsible-ai-collaborative/aiid/issues/2933
- [x] https://github.com/responsible-ai-collaborative/aiid/issues/2934
- [x] https://github.com/responsible-ai-collaborative/aiid/issues/2948
- [x] https://github.com/responsible-ai-collaborative/aiid/issues/2964
- [x] https://github.com/responsible-ai-collaborative/aiid/issues/2966
- [x] https://github.com/responsible-ai-collaborative/aiid/issues/2968
- [x] https://github.com/responsible-ai-collaborative/aiid/issues/2983
- [x] https://github.com/responsible-ai-collaborative/aiid/issues/3028
- [x] https://github.com/responsible-ai-collaborative/aiid/issues/3058
- [x] https://github.com/responsible-ai-collaborative/aiid/issues/3059
- [x] https://github.com/responsible-ai-collaborative/aiid/issues/3060
- [x] https://github.com/responsible-ai-collaborative/aiid/issues/3061
- [x] https://github.com/responsible-ai-collaborative/aiid/issues/3062
- [x] https://github.com/responsible-ai-collaborative/aiid/issues/3063
- [x] https://github.com/responsible-ai-collaborative/aiid/issues/3064
- [x] https://github.com/responsible-ai-collaborative/aiid/issues/3065
- [x] https://github.com/responsible-ai-collaborative/aiid/issues/3066
- [x] https://github.com/responsible-ai-collaborative/aiid/issues/3067
- [x] https://github.com/responsible-ai-collaborative/aiid/issues/3068
- [x] https://github.com/responsible-ai-collaborative/aiid/issues/3069
- [x] https://github.com/responsible-ai-collaborative/aiid/issues/3070
- [x] https://github.com/responsible-ai-collaborative/aiid/issues/3071
- [x] https://github.com/responsible-ai-collaborative/aiid/issues/3072
- [x] https://github.com/responsible-ai-collaborative/aiid/issues/3073
- [x] https://github.com/responsible-ai-collaborative/aiid/issues/3074
- [x] https://github.com/responsible-ai-collaborative/aiid/issues/3075
- [x] https://github.com/responsible-ai-collaborative/aiid/issues/3076
- [x] https://github.com/responsible-ai-collaborative/aiid/issues/3077
- [x] https://github.com/responsible-ai-collaborative/aiid/issues/3078
- [x] https://github.com/responsible-ai-collaborative/aiid/issues/3079

Previously: _In evaluating if Playwright is good for us, we proposed that each of us should try converting some Cypress tests to Playwright to get a feel for the framework, the time involved in converting, and to potentially evaluate the speed/efficiency of Playwright tests._

_Let's start by each picking 1 "simple" test and 1 "more difficult"/complicated test to convert, once we have the proper directory setup:_

**Comment by clari182** [comment]
Cypress migration to playwright done ✨

**Comment by pdcp1** [comment]
🥳

**Comment by smcgregor** [comment]
🥳
