### ISSUE TITLE
Tailwind CSS Adoption

### ISSUE THREAD

**Issue by smcgregor** [responsible-ai-collaborative/aiid#604]
**Why?**

The visual style of the AIID is largely a highly hacked version of the [Gatsby Gitbook Starter](https://www.gatsbyjs.com/starters/hasura/gatsby-gitbook-starter), but the visual style of the website has grown stale, inconsistent, and slow to iterate. Some of the components are built on top of [Bootstrap](https://react-bootstrap.github.io/), and others are highly customized local CSS for specific applications. Improving the look/feel and iterating the site would benefit from the adoption of a uniform style for the components, particularly the landing page and the citation pages. Enter Tailwind CSS,

> Tailwind CSS is basically a utility-first CSS framework for rapidly building custom user interfaces. It is a highly customizable, low-level CSS framework that gives you all of the building blocks you need to build bespoke designs without any annoying opinionated styles you have to fight to override. ([read more](https://tailwindcss.com/))

Tailwind CSS is [MIT Licensed](https://github.com/tailwindlabs/tailwindcss/blob/master/LICENSE), and the company behind it also has a collection of [premium React component code](https://tailwindui.com/) that is effectively boilerplate demonstration of how you can use the MIT-licensed CSS library. Effectively, the premium react components are like the book about Tailwind CSS and is subject to copyright, but once you port examples to your own use case and presentation it does not make your open source project subject to the non-MIT licensed examples (please comment if this is the case and we will avoid Tailwind CSS entirely).

So, in this issue we will adopt TailwindCSS and individual developers can either use TailwindUI (the premium code examples) or develop their own use cases of TailwindUI and avoid licensing the examples. If you have a practical need for TailwindsUI and are actively developing source code on top of the AIID codebase, please reach out and we will see if we can provide a license consistent with TailwindLabs licensing requirements.

**What**

This issue has the following steps, each of which should be separate pull requests made against the `staging` branch.

1. [ ] Install TailwindCSS https://tailwindcss.com/docs/guides/gatsby
2. [ ] Port the blog listing (https://incidentdatabase.ai/blog) to use Tailwind in the main content area
3. [ ] Port the citation pages (e.g., https://incidentdatabase.ai/cite/1) to use Tailwind in the main content area
4. [ ] Port landing page (https://incidentdatabase.ai/) to use Tailwind in the main content area
5. [ ] Port the incident report cards on the Discover application to use Tailwind (https://incidentdatabase.ai/apps/discover)
6. [ ] Port the banner at the top of the page to use Tailwind
7. [ ] Port the footer at the bottom of the page to use Tailwind (also add a link to the launch report)
8. [ ] Port all remaining stylistic inconsistencies to match the emerging Tailwind style
9. [ ] Port the navigation structure of the website (the left bar) to use Tailwind
10. [ ] [Board the ship ;)](https://en.wikipedia.org/wiki/Ship_of_Theseus)

Each of these steps should produce design that is either consistent with a free snippet from TailwindUI or copy over a snippet in a manner compliant with a license.

**Comment by cesarvarela** [comment]
The Tailwind UI team released some new templates, might serve as inspiration:

[Syntax](https://click.convertkit-mail.com/qduq05dl37h7h77o8xlal/wnh2hghr6wdvnpi7/aHR0cHM6Ly9zeW50YXgudGFpbHdpbmR1aS5jb20v) — a documentation site template powered by Stripe's new [Markdoc](https://click.convertkit-mail.com/qduq05dl37h7h77o8xlal/reh8hohqz0pv4la2/aHR0cHM6Ly9tYXJrZG9jLmlvLw==) library that's perfect for things like open-source projects or product documentation.
[Primer](https://click.convertkit-mail.com/qduq05dl37h7h77o8xlal/08hwh9hmrd4wv3ul/aHR0cHM6Ly9wcmltZXIudGFpbHdpbmR1aS5jb20v) — a landing page template for ebooks and courses that bakes in a lot of the best practices we've learned releasing our own info products.
[Salient](https://click.convertkit-mail.com/qduq05dl37h7h77o8xlal/8ghqhohgnl8pzrfk/aHR0cHM6Ly9zYWxpZW50LnRhaWx3aW5kdWkuY29tLw==) — a stunning but simple SaaS marketing website you can quickly adapt for your next idea without burning time you wish you were spending on the actual product.
[Keynote](https://click.convertkit-mail.com/qduq05dl37h7h77o8xlal/vqh3hrhnrp63lqbg/aHR0cHM6Ly9rZXlub3RlLnRhaWx3aW5kdWkuY29tLw==) — a beautiful conference website design that works just as well for small local gatherings as it does for international events.
[Transmit](https://click.convertkit-mail.com/qduq05dl37h7h77o8xlal/l2hehmho73pvept6/aHR0cHM6Ly90cmFuc21pdC50YWlsd2luZHVpLmNvbS8=) — an awesome podcasting template with a custom persistent audio player that you can wire up to your own RSS feed in no time.[Syntax](https://click.convertkit-mail.com/qduq05dl37h7h77o8xlal/wnh2hghr6wdvnpi7/aHR0cHM6Ly9zeW50YXgudGFpbHdpbmR1aS5jb20v) — a documentation site template powered by Stripe's new [Markdoc](https://click.convertkit-mail.com/qduq05dl37h7h77o8xlal/reh8hohqz0pv4la2/aHR0cHM6Ly9tYXJrZG9jLmlvLw==) library that's perfect for things like open-source projects or product documentation.
[Primer](https://click.convertkit-mail.com/qduq05dl37h7h77o8xlal/08hwh9hmrd4wv3ul/aHR0cHM6Ly9wcmltZXIudGFpbHdpbmR1aS5jb20v) — a landing page template for ebooks and courses that bakes in a lot of the best practices we've learned releasing our own info products.
[Salient](https://click.convertkit-mail.com/qduq05dl37h7h77o8xlal/8ghqhohgnl8pzrfk/aHR0cHM6Ly9zYWxpZW50LnRhaWx3aW5kdWkuY29tLw==) — a stunning but simple SaaS marketing website you can quickly adapt for your next idea without burning time you wish you were spending on the actual product.
[Keynote](https://click.convertkit-mail.com/qduq05dl37h7h77o8xlal/vqh3hrhnrp63lqbg/aHR0cHM6Ly9rZXlub3RlLnRhaWx3aW5kdWkuY29tLw==) — a beautiful conference website design that works just as well for small local gatherings as it does for international events.
[Transmit](https://click.convertkit-mail.com/qduq05dl37h7h77o8xlal/l2hehmho73pvept6/aHR0cHM6Ly90cmFuc21pdC50YWlsd2luZHVpLmNvbS8=) — an awesome podcasting template with a custom persistent audio player that you can wire up to your own RSS feed in no time.

**Comment by smcgregor** [comment]
+1 for inspiration, but likely not for adoption outright.

**Comment by clari182** [comment]
Task list / completion 

- [ ]  Install TailwindCSS https://tailwindcss.com/docs/guides/gatsby
- [ ]  Port the blog listing (https://incidentdatabase.ai/blog) to use Tailwind in the main content area
- [ ]  Port the citation pages (e.g., https://incidentdatabase.ai/cite/1) to use Tailwind in the main content area
- [ ]  Port landing page (https://incidentdatabase.ai/) to use Tailwind in the main content area
- [ ]  Port the incident report cards on the Discover application to use Tailwind (https://incidentdatabase.ai/apps/discover)
- [ ]  Port the banner at the top of the page to use Tailwind
- [ ]  Port the footer at the bottom of the page to use Tailwind (also add a link to the launch report)
- [ ]  Port all remaining stylistic inconsistencies to match the emerging Tailwind style
- [ ]  Port the navigation structure of the website (the left bar) to use Tailwind
- [ ]  [Board the ship ;)](https://en.wikipedia.org/wiki/Ship_of_Theseus)

**Comment by smcgregor** [comment]
Closing this as a top level tracking issue.
