### ISSUE TITLE
Multi-lingual support

### ISSUE THREAD

**Issue by cesarvarela** [responsible-ai-collaborative/aiid#695]
We'll split the development of this feature into two main areas: 

Content

- [x]  reports' fields `title` & `text` https://github.com/responsible-ai-collaborative/aiid/issues/693
- [ ] incidents' `title` & `description (After first launch) (opened https://github.com/responsible-ai-collaborative/aiid/issues/976)
- [x] blog posts https://github.com/responsible-ai-collaborative/aiid/pull/743
- [x] submissions & reports `language` field https://github.com/responsible-ai-collaborative/aiid/issues/626

UI

- [x] Discover app https://github.com/responsible-ai-collaborative/aiid/pull/731
- [x] Cite pages https://github.com/responsible-ai-collaborative/aiid/issues/764
- [x] Navigation - https://github.com/responsible-ai-collaborative/aiid/issues/773
- [x] Content pages (`/content/**/*.mdx`)
- [x] Landing Page https://github.com/responsible-ai-collaborative/aiid/issues/766
- [x] Submit Form https://github.com/responsible-ai-collaborative/aiid/issues/806
- [x] Review queue
- [ ] Support different date formats https://github.com/responsible-ai-collaborative/aiid/issues/803
- [x] Add a language selector to the header https://github.com/responsible-ai-collaborative/aiid/issues/832

Docs

- [x] Documentation #831 

Tests

...

Let's track the general discussion of i18n support here.

**Comment by cesarvarela** [comment]
Closing since key functionality is live.

**Comment by smcgregor** [comment]
🎆 😃 🎆
