### ISSUE TITLE
Demonstrations of AI System Failures

### ISSUE THREAD

**Issue by smcgregor** [responsible-ai-collaborative/aiid#724]
The current criteria admits both harms and near harms, but incidents like https://incidentdatabase.ai/cite/12 don't fit -- it is a demonstration of a weakness present in a very common modeling approach. It does and will have many incidents in the real world demonstrating that it is "real," but these lab results don't pass the current criteria and the single report attached to this incident would be more appropriately attached to an incident that involves vector embeddings (maybe https://incidentdatabase.ai/cite/37 ). The difficult thing is that most of the time we will not know the exact system type being employed. So these demonstrations of incidents-in-waiting, AKA "recalls" in other industries, may not ever get attached to an incident even when it could be informative...

I think when we are ingesting these incident reports in the future, we should attach it to an incident that has already been reported (if it exists). If it does not exist, then we should create a new incident for it, and in the forthcoming "related incidents" feature @lmcnulty is working on we can cross reference the earlier demonstration of the system failure.

The options for instances when there is not a real world incident to attach to are,

a) Expand the criteria to include these "recall like" incidents (Demonstrated "weakness" maybe?)
b) Create a new first class report type (e.g., something like "demonstration") and keep it separate from the incidents
c) Only add these reports to real world harms or near harms as context
d) Don't add these reports to the DB at all
e) Create a catchall collection of reports that don't fit the criteria, but are still useful to index. This will allow for building the knowledge base while not getting in the way of operating a rigorously collected database

I am leaning towards (a) or (e) here.

CC @LKchemposer

**Comment by smcgregor** [comment]
(Cross posted from Slack)

Hi @channel, something we have been discussing for quite some time in the dataset side of the AIID is the problem of incident definition. In particular, separating incidents where something has happened in the real world, and where someone demonstrates there is a problem with a technology absent of a harmed party. @Daniel Atherton referred to this in an email as an “incident in waiting.” In other settings, it could be referred to as a “recall” or a “vulnerability.” I believe there is consensus among those I have spoken to for including these non-incident reports in some form since they serve our change thesis and userbase. Further, they are often subsequently associated with real world realizations of those previously discovered issues.

<< Request >>

1. Please raise any objections you may have to expanding to a class of reports that are not incidents. Please presume that the additional class of reports will be easy to segment (via the user interface) from the original and ongoing collection of incidents and their reports.

2. Indicate your preferred name and scope for the expansion in coverage. I will put forward, “issue report”, “context report”, “case report”, “vulnerability report”, “briefing report”, “recall report”, <your proposal here>.

Please discuss on the GitHub issue [0] or on Slack.

[0] https://github.com/responsible-ai-collaborative/aiid/issues/724

**Comment by Janetbananet** [comment]
For what it's worth since I'm new and not an expert in the field at this point: I like option e. These types of reports certainly seem relevant and useful, but since they are not incidents don't quite fit (yet). But collecting them in one place allows for associating them with related incidents when they happen, or perhaps there are other uses down the road not quite visible yet.

**Comment by kepae** [comment]
coming over from #449, I like option (e). The thesis of tracking incidents is to avoid repeating mistakes and create learning opportunities, and these quasi-incidents/uncertainties can serve that.

I'd like to distinguish between AI-related events that _have already_ happened and events that _may_ happen, though. An incident DB can categorize the former, and it would be handy to have a term. However, a "recall report" sounds like something went to market and action was taken, which may or may not be the case when describing past (quasi-)incidents. [Incident #12](https://incidentdatabase.ai/cite/12) smells of a supply chain-like issue that may result in future incidents (or already has!) but we don't have a report to condense this context onto.

That classification aside, the idea to have an "expansion" in coverage that is meant to address this uncertainty is awesome. I think "context report" is most forgiving and doesn't bring in a market-based notion just yet.

**Comment by LKchemposer** [comment]
I'd like to propose an expansion to the system of reports and a taxonomy scheme, which is developed based on my experience in deep diving into 200+ incidents and their reports.

Report taxonomy
---

From what I have seen in the database, reports tend to fall into 3 large categories: **Context - Incident - Follow-up**

1. **Context reports** discuss context, concerns, or known harms, etc., _prior to_ the incident.

- _Sub-types:_
  1. Vulnerability reports: fit better for security-related incidents (e.g., Tesla Autopilot's vulnerabilities in [incident 159](https://incidentdatabase.ai/cite/159))
  2. Projected-harm reports: discuss harms that _may_ happen, or known harms/issues of a particular technology but without a particular deployer (e.g., gender bias in NLP in [incident 12](https://incidentdatabase.ai/cite/12), popularity bias in recommendation systems in [incident 168](https://incidentdatabase.ai/cite/168))
- _Criteria:_
  1. Does not necessarily satisfy the criteria of incident
  2. Can be admitted, but cannot be treated as an "incident" (e.g., not assigned an incident id)
- _Forms:_ e.g., journal articles - most likely, news articles

2. **Incident reports** discuss the incident events in detail and is the frame of reference for the other two

- _Criteria:_
  1. Must strictly satisfy the criteria of incident
  2. Must be present for an incident to be an "incident"
- _Forms:_ e.g., audit reports (e.g., VioGen's audit in [incident 186](https://incidentdatabase.ai/cite/186#r1591)), news articles - most likely, journal articles - rare, YouTube videos, social media posts

3. **Follow-up reports** discuss any events _following_ the core incident event that are related to the incident

- _Criteria:_
  1. Does not necessarily satisfy the criteria of incident
  2. Must be related to an incident
- _Forms:_ e.g., news reports, recall reports (e.g., Tesla's rolling stop recall in [incident 209](https://incidentdatabase.ai/cite/209#r629da7979e8fc9073246a405)), company responses, government interventions (e.g.,  AV testing permit suspension in [incident 151](https://incidentdatabase.ai/cite/151#r1707)), on-going lawsuits

**Note:** a report can fall into 1, 2, or all 3 of these types.

Benefits
---

1. Builds upon what we've already discussed here
2. As far as I know, does not contradict the backend development of a new type of report
3. Makes it easier for editors to determine whether a report that does not satisfy current incident criteria can still be admitted either as a context report or a follow-up report
4. Admits harms and near-harms, but treats them separately
5. Models reports along trajectory of an incident, but allows for flexibility

**Comment by smcgregor** [comment]
@LKchemposer I think your proposal has elements of both a taxonomy that would be applied to reports (as opposed to incidents) and criteria grouping reports as is the case with the incident criteria. I don't think we should mix these two concepts. A follow-up report can be associated with the incident it is following and that follow-up report could be labeled as such. The reports as they are currently ingested have the ability to be tagged, and those tags could be formally defined and applied across the report base.

What are your first reactions to "incidents and issues" instead of incidents and context?

**Comment by smcgregor** [comment]
@cesarvarela is getting closer to working this issue and while we still need to adopt a definition and criteria, it is time to get moving on the engineering front. The design I give below is for César to implement, then we will graft definitions and criteria on top before shipping the feature. I am going to presume we will have two record types moving forward,

1) Incidents  
2) Non-incidents. Let's call these "issues" for now, but we will revisit the name in discussion with @kepae . We just need a name to move forward with now.

Database design changes implied by this are,

1. [ ] Submissions in the submit form should have a toggle that defaults to "incident" and additionally has the option of selecting "issue". If "issue" is selected, the form should not display the incident-associated fields.
2. [ ] Make all reports in the report collection orphan-able, meaning that they can be associated with incidents in the incident collection, but that is optional
3. [ ] Make it possible for reports to be associated with multiple incidents. Some incident reports actually talk about multiple incidents
4. [ ] Make all reports have a boolean value, `is_incident_report`, and require it to be set to `true` for all the current reports. It should be set to `false` if the report is not associated with any incident
5. [ ] Add some tests to CI that confirms the requirement that `is_incident_report` is `true` whenever it is associated with one or more incidents, and `false` otherwise
6. [ ] Update the Algolia index such that the reports can be associated with multiple incidents. I think this involves changing it to an array type
7. [ ] Add a toggle to the `discover` app that says `Display Issues`. This should default to false at the outset, but there will be a lot more downstream design here.
8. [ ] The new type of reports in the discover app should link to a page that shows the complete report in isolation. This should just be the report card that is in the citation page at the moment -- we want to use a many of the components for `incidents` as possible here
9. [ ] All reports should have the ability to add/remove to/from existing incidents on the report edit page
10. [ ] We need a form that allows for creating a new incident not from the promotion of a new report

This is a database structure discussion in addition to the definitional questions, @cesarvarela feel free to discuss the above steps!

**Comment by smcgregor** [comment]
Also, @npit, your work plugs into these changes. Most "Issue reports" that are not meeting the incident definition have a task and technology, which means they will be classifiable and we will be able to generate reports on them. I am going to place this out of scope for the current design, which presumes that classifications are applied at the incident level. However, we should open a tracking issue around this after we have an incident-scoped hierarchical taxonomy in place.

**Comment by cesarvarela** [comment]
@smcgregor, can it happen that a report with `is_incident_report: false` be updated to be linked with an incident? 

Should the flag be updated to `true`?

And when the opposite? Should this flag be `true` if I unlink a report from its incident?

**Comment by smcgregor** [comment]
@cesarvarela yes. Depending on your implementation, you might also not include the flag. However, I believe it will have its uses.

**Comment by smcgregor** [comment]
This is in production now. See also: https://arxiv.org/abs/2211.10384
